把剩的汉化了
LittleChest/HeartFire pull request #11
Opened 2024-06-23 13:17 UTC by HeimNad

2024-06-23 15:24 UTC, LittleChest requested changes

2024-06-23 15:24 UTC, LittleChest commented on .vitepress/en.ts
>    root: {
应改为en

2024-06-24 16:33 UTC, HeimNad commented
别急
我在上个commit

2024-06-25 02:52 UTC, LittleChest commented on src/index.md
> +    avatar: 'https://littleskin.cn/avatar/player/XieXiLin',
en没有这样修改

2024-06-25 02:53 UTC, HeimNad commented on src/index.md
> +    avatar: 'https://littleskin.cn/avatar/player/XieXiLin',
没逝, 你来

2024-06-25 02:55 UTC, merged